# Generated by Django 3.2.5 on 2021-07-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('diy', 'DIY'), ('character inspired', 'Character Inspired'), ('caniafe orginals', 'Caniafe Originals')], max_length=80, null=True)),
            ],
        ),
    ]
