# Generated by Django 3.2.5 on 2021-07-31 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cof', '0002_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=150)),
                ('content', models.TextField()),
            ],
        ),
    ]
